### PR TITLE
Convert to manifest v3

### PR DESCRIPTION
**Pull request by Friss**
Seems to work on mac so far

### CODE REVIEW

**Comment by LangLangBart** [comment]
### nullish coalescing
could it be that the double question mark (nullish coalescing) is missing ?

```diff
--- a/extension/scripts/background.js
+++ b/extension/scripts/background.js
@@ -56,7 +56,8 @@ const fetchStreamerStatus = async (

   const knownOnlineStreamers = (
     await chrome.storage.local.get(['knownOnlineStreamers'])
-  ).knownOnlineStreamers;
+  ).knownOnlineStreamers ?? {};

   for (let streamer of Object.keys(knownOnlineStreamers)) {
     if (!streamersLive[streamer]) {
```

### Logs
without it, i would get an error, you may have to delete your local storage to reproduce the issue.


```log
background.js:62 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at fetchStreamerStatus (background.js:62:31)
```

**Comment by LangLangBart** [comment]
### Description - lowerCase

The problem from #15 is not solved yet, when I add a username with capital letters it stays red (even if the streamer is online).

### Solution

```diff
--- a/extension/scripts/pop-up.js
+++ b/extension/scripts/pop-up.js
@@ -14,7 +14,7 @@ const fetchStreamerStatus = (storage) => {
     chrome.runtime
       .sendMessage({
         action: 'fetchStreamerStatus',
-        usernames: Array.from(new Set(storage.twitchStreams)),
+        usernames: [...new Set(storage.twitchStreams.map(username=>username.toLowerCase()))],
       })
       .then((response) => {
         displayStreamerStatus(response);
@@ -208,7 +208,7 @@ document.addEventListener('DOMContentLoaded', () => {
       const streamer = evt.target.getAttribute('data-username');

       chrome.storage.sync.get('twitchStreams', (storage) => {
-        const index = storage.twitchStreams.indexOf(streamer);
+        const index = storage.twitchStreams.findIndex(item => item.toLowerCase() === streamer.toLowerCase());

         if (index >= 0) {
           storage.twitchStreams.splice(index, 1);
```

### Alternative solution
This solution would also work, but not for streamers that were added with capital letters before this patch.

```diff
--- a/extension/scripts/background.js
+++ b/extension/scripts/background.js
@@ -48,7 +48,7 @@ const fetchStreamerStatus = async (
       Accept: 'application/json',
     },
     body: JSON.stringify({
-      channels: usernames.map((username) => username.toLowerCase()),
+      channels: usernames,
     }),
   });

--- a/extension/scripts/pop-up.js
+++ b/extension/scripts/pop-up.js
@@ -159,7 +159,7 @@ document.addEventListener('DOMContentLoaded', () => {

   document.getElementById('addForm').addEventListener('submit', (evt) => {
     evt.preventDefault();
-    const user = document.getElementById('streamerUsername').value;
+    const user = document.getElementById('streamerUsername').value.toLowerCase();
     if (user) {
       chrome.storage.sync.get('twitchStreams', (storage) => {
         storage.twitchStreams.push(user);
```

**Comment by LangLangBart** [comment]
I would prefer to see the `stream.user_name`, rather than `stream.channel.display_name` in the `pop-up.js`, as this would show the user name with upper case letters as seen in the web UI.

user_name


trymacs

**Comment by Friss** [comment]
Thanks for the review @LangLangBart (suuuuper late reply by me) great suggestions

**Pull request merged**
